### PR TITLE
Team5 review

### PR DESCRIPTION
**Pull request by Weeblin**
No new content, fix coherence and syntax. Has communicated to Jeremy.

### CODE REVIEW

**Review by jl21518 — APPROVED** [review]

**Comment by Weeblin** [comment]
It's okay Jeremy will view our minor report in pdf, thanks everyone.

**Comment by BusterBlack** [comment]
> It's okay Jeremy will view our minor report in pdf, thanks everyone.

what was this PR about? did we miss something????

**Comment by Weeblin** [comment]
> > It's okay Jeremy will view our minor report in pdf, thanks everyone.
> 
> what was this PR about? did we miss something????

Hi, it was a mitigated circumstance given to our group, if you could help us merge this and resubmit that'll be nice, there won't be any concern to the rest of the group. We've talked to Jeremy and he will recognise it if you state that this is due to team5's issue. Thank you.

**Comment by BusterBlack** [comment]
ok i will merge and send it to Pitt saying that. Are there only changes to your section? theres seems to be changes all over the places

**Comment by BusterBlack** [comment]
you've got some hardcoded references in there... could you change them to \cite{} style to be sure they're correct.... i not sure what you are citing, or i'd do it

**Comment by Weeblin** [comment]
> you've got some hardcoded references in there... could you change them to \cite{} style to be sure they're correct.... i not sure what you are citing, or i'd do it

Hi, we have just fixed that cite thing, everything is ready. And up to the commit that you merged last time, I don't seem to find any changes outside of team5's .tex🤔

**Review by BusterBlack — APPROVED** [review]
LGTM

**Pull request merged**
